exception ClassFormatError of string
exception IllegalAccessError
exception ClassNotFoundException
exception LinkageError
exception UnsupportedClassVersionError
exception NoClassdefFoundError
exception IncompatibleClassChangeError
exception ClassCircularityError
