exception ClassFormatError of string
exception IllegalAccessError
exception ClassNotFoundException of string
exception LinkageError
exception UnsupportedClassVersionError
exception NoClassdefFoundError
exception IncompatibleClassChangeError
exception ClassCircularityError
exception NoSuchFieldError
exception NoSuchMethodError of string
exception VirtualMachineError
exception NullPointerException
exception ArrayIndexOutOfBoundsException
exception InstantiationError
exception NegativeArraySizeException
